//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationDatabase) DeepCopyInto(out *DestinationDatabase) {
	*out = *in
	if in.DbCredentialsSecret != nil {
		in, out := &in.DbCredentialsSecret, &out.DbCredentialsSecret
		*out = new(v1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationDatabase.
func (in *DestinationDatabase) DeepCopy() *DestinationDatabase {
	if in == nil {
		return nil
	}
	out := new(DestinationDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Migratedb) DeepCopyInto(out *Migratedb) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Migratedb.
func (in *Migratedb) DeepCopy() *Migratedb {
	if in == nil {
		return nil
	}
	out := new(Migratedb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Migratedb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigratedbList) DeepCopyInto(out *MigratedbList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Migratedb, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigratedbList.
func (in *MigratedbList) DeepCopy() *MigratedbList {
	if in == nil {
		return nil
	}
	out := new(MigratedbList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigratedbList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigratedbSpec) DeepCopyInto(out *MigratedbSpec) {
	*out = *in
	in.SourceDb.DeepCopyInto(&out.SourceDb)
	if in.DestinationDb != nil {
		in, out := &in.DestinationDb, &out.DestinationDb
		*out = make([]DestinationDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IncludeTable != nil {
		in, out := &in.IncludeTable, &out.IncludeTable
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeTable != nil {
		in, out := &in.ExcludeTable, &out.ExcludeTable
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigratedbSpec.
func (in *MigratedbSpec) DeepCopy() *MigratedbSpec {
	if in == nil {
		return nil
	}
	out := new(MigratedbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigratedbStatus) DeepCopyInto(out *MigratedbStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigratedbStatus.
func (in *MigratedbStatus) DeepCopy() *MigratedbStatus {
	if in == nil {
		return nil
	}
	out := new(MigratedbStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceDatabase) DeepCopyInto(out *SourceDatabase) {
	*out = *in
	if in.DbCredentialsSecret != nil {
		in, out := &in.DbCredentialsSecret, &out.DbCredentialsSecret
		*out = new(v1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceDatabase.
func (in *SourceDatabase) DeepCopy() *SourceDatabase {
	if in == nil {
		return nil
	}
	out := new(SourceDatabase)
	in.DeepCopyInto(out)
	return out
}
