---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - k8s-dbmigrator.k8sdbsync
  resources:
  - migratedbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-dbmigrator.k8sdbsync
  resources:
  - migratedbs/finalizers
  verbs:
  - update
- apiGroups:
  - k8s-dbmigrator.k8sdbsync
  resources:
  - migratedbs/status
  verbs:
  - get
  - patch
  - update
